# Generated by Django 2.1.1 on 2018-09-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('ispublic', models.BooleanField(default=False)),
                ('public_id', models.CharField(max_length=16)),
                ('friendly_url', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=8)),
                ('nickname', models.CharField(max_length=32)),
                ('public_id', models.CharField(max_length=16)),
                ('bio', models.TextField()),
            ],
        ),
    ]
