# Generated by Django 2.1.1 on 2018-09-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('public_id', models.CharField(max_length=16)),
                ('friendly_url', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=8)),
                ('maps', models.ManyToManyField(blank=True, related_name='maps', to='mindmaps.Map')),
            ],
        ),
        migrations.RemoveField(
            model_name='usersmaps',
            name='maps',
        ),
        migrations.RemoveField(
            model_name='usersmaps',
            name='user',
        ),
        migrations.DeleteModel(
            name='UsersMaps',
        ),
    ]
