# Generated by Django 2.1.1 on 2018-12-18 13:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40)),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 12, 18, 13, 17, 27, 455008))),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapviews', to='mindmaps.Map')),
            ],
        ),
    ]
