# Generated by Django 2.1.1 on 2018-09-02 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0002_map_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maps', models.ManyToManyField(blank=True, related_name='maps', to='mindmaps.Map')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mindmaps.User')),
            ],
        ),
    ]
