# Generated by Django 2.1.1 on 2018-10-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0002_auto_20180909_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='mapjson',
            field=models.TextField(default=''),
        ),
    ]
