# Generated by Django 2.1.1 on 2019-01-03 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0002_mapview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapview',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 3, 1, 17, 59, 94157)),
        ),
    ]
