# Generated by Django 2.1.1 on 2019-01-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0004_auto_20190103_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapview',
            name='session',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
