# Generated by Django 2.1.1 on 2018-11-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0004_auto_20181027_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
