# Generated by Django 2.1.1 on 2018-11-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0005_map_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='imageurl',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
